### ISSUE TITLE
Latest PuDB (2017.1.3) dies with ListBoxError in some cases

### ISSUE THREAD

**Issue by cdman** [inducer/pudb#271]
Stacktrace (edited slightly for anonymity):

```
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File ".../site-packages/pudb/debugger.py", line 160, in dispatch_line
    self.user_line(frame)
  File ".../site-packages/pudb/debugger.py", line 381, in user_line
    self.interaction(frame)
  File ".../site-packages/pudb/debugger.py", line 349, in interaction
    show_exc_dialog=show_exc_dialog)
  File ".../site-packages/pudb/debugger.py", line 2084, in call_with_ui
    return f(*args, **kwargs)
  File ".../site-packages/pudb/debugger.py", line 2322, in interaction
    self.event_loop()
  File ".../site-packages/pudb/debugger.py", line 2280, in event_loop
    canvas = toplevel.render(self.size, focus=True)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 2085, in render
    focus = focus and self.focus_position == i)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/listbox.py", line 489, in render
    raise ListBoxError, "Widget %r at position %r within listbox calculated %d rows but rendered %d!"% (widget,w_pos,w_rows, canvas.rows())
ListBoxError: Widget <VariableWidget selectable flow widget> at position 3 within listbox calculated 1 rows but rendered 0!
```

This happens under Ubuntu 17.04 using Gnome Terminal (pudb is being run inside of a docker container also running Ubuntu 17.04 if it matters). The error goes away when using PuDB 2017.1.2. It also seems to be dependent on the terminal size. For example it happens both with my "maximized" terminal size (158x46) as well as at 132x43, but it does not happen when the terminal is resized to 80x24. My pudb.cfg:

```
[pudb]
breakpoints_weight = 1
current_stack_frame = top
custom_shell = 
custom_stringifier = 
custom_theme = 
display = auto
line_numbers = True
prompt_on_quit = True
seen_welcome = e032
shell = internal
sidebar_width = 0.5
stack_weight = 1
stringifier = type
theme = classic
variables_weight = 1
wrap_variables = True
```

This is also potentially related to #269

**Comment by inducer** [comment]
c9eb5960164cc39b937df4f2ecf2eb9062afde95 is the only commit between 2017.1.2 and 2017.1.3 that even gets close to this code. @asmeurer, could you take a look?

**Comment by asmeurer** [comment]
@cdman can you tell us what the contents of the variable is (according to the traceback, it's the 3rd variable)?

**Comment by asmeurer** [comment]
Oh maybe the wrapping code also needs to be using calc_width.

**Comment by asmeurer** [comment]
I get something that is possibly the same issue

```
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/pudb/pudb/__init__.py", line 93, in runscript
    dbg._runscript(mainpyfile)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 432, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "test2.py", line 2, in <module>
    b = 1
  File "test2.py", line 2, in <module>
    b = 1
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 160, in dispatch_line
    self.user_line(frame)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 381, in user_line
    self.interaction(frame)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 349, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2089, in call_with_ui
    return f(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2330, in interaction
    self.event_loop()
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2288, in event_loop
    canvas = toplevel.render(self.size, focus=True)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/container.py", line 2085, in render
    focus = focus and self.focus_position == i)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/listbox.py", line 473, in render
    focus_canvas = focus_widget.render((maxcol,), focus=focus)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/aaronmeurer/Documents/pudb/pudb/var_view.py", line 164, in render
    return make_canvas(text, attr, maxcol, apfx+"value")
  File "/Users/aaronmeurer/Documents/pudb/pudb/ui_tools.py", line 48, in make_canvas
    maxcol=maxcol)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/urwid/canvas.py", line 356, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified 
47
[90, 47]
[b"a: '\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad", b"  \xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87\xe4\xb8\xad\xe6\x96\x87'          "]
```

From

```py
a = '中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文中文'
b = 1
```

**Comment by asmeurer** [comment]
@cdman also can you test if you still get the error if you turn off "wrap variables" in the settings (Ctrl-p)?

**Comment by asmeurer** [comment]
@cdman can you test my `text_width` branch? It doesn't fix my issue, but I'm not sure if it's really the same issue.

**Comment by asmeurer** [comment]
I found a fix for my traceback (in my `text_width` branch). @cdman would be great if you could confirm if my `text_width` branch fixes your issue too. And regardless if it fixes it, I'd like to know what the variable in question so I can write a test if it's fixed, or debug it if it isn't.

**Comment by cdman** [comment]
@asmeurer - thank you for the quick turn-around. Trying to answer some of your questions:

- yes, PuDB still dies, even when turning off "Wrap variables", but with a different exception (added at the end)
- your `text_width` branch seems to solve the issue, but it might be that fe46357 fixed the issue, since...
- it doesn't happen on inducer/pudb master either and
- the variable types you were asking about are:
  - the pudb module
  - a MagicMock from the mock library (python 2.7, installed from PyPI)
  - and `self` (a `django_testbed.TestCase` subclass)

```
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File ".../site-packages/pudb/debugger.py", line 160, in dispatch_line
    self.user_line(frame)
  File ".../site-packages/pudb/debugger.py", line 381, in user_line
    self.interaction(frame)
  File ".../site-packages/pudb/debugger.py", line 349, in interaction
    show_exc_dialog=show_exc_dialog)
  File ".../site-packages/pudb/debugger.py", line 2084, in call_with_ui
    return f(*args, **kwargs)
  File ".../site-packages/pudb/debugger.py", line 2322, in interaction
    self.event_loop()
  File ".../site-packages/pudb/debugger.py", line 2280, in event_loop
    canvas = toplevel.render(self.size, focus=True)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 2085, in render
    focus = focus and self.focus_position == i)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/urwid/listbox.py", line 487, in render
    canvas = widget.render((maxcol,))
  File ".../site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File ".../site-packages/pudb/var_view.py", line 214, in render
    return make_canvas(text, attr, maxcol, apfx+"value")
  File ".../site-packages/pudb/ui_tools.py", line 17, in make_canvas
    diff = maxcol - calc_width(line, 0, len(line))
TypeError: Neither unicode nor string.
```

**Comment by asmeurer** [comment]
OK, so probably I found (and fixed) an independent bug. It sounds like your issue was with the mock objects, which was indeed fixed in a separate PR already.

**Comment by jojonki** [comment]
Is this issue runnning? I am facing a similar problem in Japanese on PuDB 2017.1.4.
```
lines = ''
with open('test.txt', 'r') as f:
    lines += ''.join(f.readlines())
```
My test file and traceback.
https://gist.github.com/jojonki/11e5f1fa4e9d4fa35ec9b772871e5a7b

**Comment by asmeurer** [comment]
@jojonki it looks like my branch from #273 fixes your issue.

**Comment by jojonki** [comment]
@asmeurer 
Thank you. Your branch fixes my issue. Hope it will be merged to master.
https://github.com/asmeurer/PuDB/tree/text_width

**Comment by yssource** [comment]
# CanvasError: Canvas text is wider than the maxcol specified
The same problem still happens to me.
- python 3.6
- pudb-2017.1.4
- with Chinese characters
![screenshot from 2018-05-24 15-34-21](https://user-images.githubusercontent.com/3756334/40471129-5205b7e4-5f68-11e8-805f-696ce8a855e0.png)

**Comment by inducer** [comment]
How is 2018.1 (just released)?
